on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Pterodactyl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compress source
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r map.zip datapacks/map/
      - name: Upload and unpack tarball
        uses: rexlmanu/pterodactyl-upload-action@v2.5
        with:
          panel-host: ${{ secrets.PANEL_HOST }}
          api-key: ${{ secrets.API_KEY }}
          server-id: "59a1b187"
          #   server-ids: |
          #     5f095019
          #     7f095019
          source: "map.zip"
          #   sources: |
          #     hello.txt
          #     hello2.txt
          target: "./world/datapacks/map.zip"
          # If you want to restart the servers after successful upload
          # restart: true
          # If you want to decompress the files after successful upload
          decompress-target: false
